### ISSUE TITLE
Mark the video being a Rap / Avoid automatic subtitles 

### ISSUE THREAD

**Issue by torwag** [johnae/persway#39]
As much as I appreciate the effort that the demo video was a combined with a Rap, as much I was confused and angry about the automatic subtitles.
As it prompted "Rust motherfucker" *twice* I was on the edge of leaving and never look back and decided to hear did the speaker really say all that... 

Just turning on audio reveals that it was a Rap and all the chaotic and repeating subtitles started to make more sense.

Just to let you know that you might scare people off who do not use audio.

**Comment by johnae** [comment]
You know, it's nice if others enjoy what I built, but if they don't that's fine. I didn't build persway, or create the video, to please other people. I did it all for me and I'm making it available for free. Someone will always be offended whatever you do, no point trying to please everyone.

I am, however, open to pull requests. If you have an idea of a good way of "marking" the video somehow, submit a PR.

**Comment by johnae** [comment]
Solved by https://github.com/johnae/persway/pull/41

**Comment by torwag** [comment]
Nah, I wasn't offended, nor I wanted offending you.... I just simply wanted to let you know that your project, which is nice and which I appreciate, might be received wrong, if people just try to read the subtitles.... that's all. Rapping subtitles or subtitles of a rap, are more a curiosity which you might have not thought of, rather than a real issue. Just wanted to let you know that's all. 
No bad feelings at all.

**Comment by pinpox** [comment]
Just commenting to let you know the song is awesome and it made my day :smile: 
Would be interested to know how it was made.
