### ISSUE TITLE
Closing a single window doesn't update workspace name

### ISSUE THREAD

**Issue by kkga** [johnae/persway#4]
If you close a single window on a workspace, the workspace name keeps the title of the closed window.
I think, ideally, it would revert back to `<num>`.

**Comment by johnae** [comment]
Yeah. Would be nice to fix that. Will look into it.

**Comment by johnae** [comment]
This should be fixed by: https://github.com/johnae/persway/commit/617d60388ee78abeddb52d52cbbc0e0edaed8744

**Comment by johnae** [comment]
Ping @kkga
