### ISSUE TITLE
bug: renaming workspaces on change-layout

### ISSUE THREAD

**Issue by salkin-mada** [johnae/persway#42]
Even with **no** `-w` in the "daemon init" persway will rename a workspace called `1🦄` to `1` when using `change-layout`.

**Comment by johnae** [comment]
Ok, thanks for the report. I'll look into it.

**Comment by johnae** [comment]
@salkin-mada I see now why this happens. It's not actually about whether workspace renaming is on or off, it's about how the relayout is implemented. I have a fix in the works but don't have time until this evening to do it properly.
