### ISSUE TITLE
Can you make the opacity flag required?

### ISSUE THREAD

**Issue by rifazn** [johnae/persway#5]
Hi! Excellent program!

I don't really use the opacity feature and so I have to start persway like

    persway -wa -o1

The problem with the existing way is that a sway command for the opacity gets sent even if I don't want to use it.

Can you make this a required flag (just like workspace_renaming and autotiling) too?

**Comment by johnae** [comment]
Good suggestion. I'll make it default to 1.0 in which case persway will not tell sway to make any changes to opacity at all. I think that'll be fine for any reasonable use cases.

**Comment by johnae** [comment]
Fixed by https://github.com/johnae/persway/commit/448a0219c4e9a2716c48fd4bb1f9c46919a6e204
