### ISSUE TITLE
Allow list for opacity

### ISSUE THREAD

**Issue by Th3Whit3Wolf** [johnae/persway#6]
It would be nice to allow certain application to be exempt from opacity change when they lose focus. I watch sometimes videos with mpv in one split and program in another split. I would prefer to keep mpv's opacity at `1.0` when it's not in focus

**Comment by johnae** [comment]
I've toyed with something along these lines here: https://github.com/johnae/persway/pull/7 - you need to find proper criteria for the windows you want to skip setting opacity for. Please try it out.

**Comment by johnae** [comment]
For example, skip setting any opacity for all firefox windows would look like this:

```
persway -o0.8 -s 'app_id="firefox"'
```

The -s option can be specified multiple times.

**Comment by Th3Whit3Wolf** [comment]
This works! Out of curiosity what's preventing the PR from getting merged?

**Comment by johnae** [comment]
Mostly I just wanted you to try it out since I'm not sure I will use this functionality.

**Comment by Th3Whit3Wolf** [comment]
Yeah it works as expected

**Comment by Th3Whit3Wolf** [comment]
Actually there are some issues. It doesn't seem to work while using autolayout and workspace renaming

````shell
~/.local/share/cargo/bin/persway -a -w -o0.8 -s 'app_id="firefox"' - s 'app_id="mpv"'
```

Opacity stays at 0.8 for all non skipped windows

**Comment by johnae** [comment]
Seems you've got an issue with your command line, that last "- s" should be "-s". Alternatively you could do this:

```sh
persway -a -w -o0.8 -s 'app_id="firefox"' 'app_id="mpv"'
```

The extra space in your cmdline makes persway execute some quite odd commands which leads to opacity staying at 0.8 for all non-skipped windows.

**Comment by Th3Whit3Wolf** [comment]
Sorry that's my fault should have double check before I posted.
