### ISSUE TITLE
First time user feedback.

### ISSUE THREAD

**Issue by jeremyjjbrown** [johnae/persway#60]
First I installed via AUR and neither of the README cmds worked

```
10:15:22 detritus:~/src/github.com/johnae/persway on main
  persway -w -e '[tiling] opacity 1' -f '[tiling] opacity 0.95; opacity 1' -l 'mark --add _prev' --autolayout
error: Found argument '-e' which wasn't expected, or isn't valid in this context

USAGE:
    persway --workspace-renaming

For more information try --help

10:15:33 detritus:~/src/github.com/johnae/persway on main
  persway daemon -w -e '[tiling] opacity 1' -f '[tiling] opacity 0.95; opacity 1' -l 'mark --add _prev' --default-layout spiral
error: Found argument 'daemon' which wasn't expected, or isn't valid in this context

USAGE:
    persway [FLAGS] [OPTIONS]

For more information try --help
```

Then I built via cargo build and I had to give sudo to creat the socket which is not really ok.
 
```
10:11:02 detritus:~/src/github.com/johnae/persway on main
  ./target/debug/persway daemon -w -e '[tiling] opacity 1' -f '[tiling] opacity 0.95; opacity 1' -l 'mark --add _prev' -d stack_main
[2023-05-16T15:11:05Z ERROR persway::server::daemon] Unable to remove stale socket: /run/user/1000/persway-wayland-1.sock
    Custom { kind: NotFound, error: VerboseError { source: Os { code: 2, kind: NotFound, message: "No such file or directory" }, message: "could not remove file `/run/user/1000/persway-wayland-1.sock`" } }
^C
```

Then I used sudo
```
  sudo ./target/debug/persway daemon -w -e '[tiling] opacity 1' -f '[tiling] opacity 0.95; opacity 1' -l 'mark --add _prev' -d stack_main
[2023-05-16T15:16:47Z ERROR persway::utils] Missing XDG_RUNTIME_DIR environment variable
[2023-05-16T15:16:47Z ERROR persway::utils] Missing WAYLAND_DISPLAY environment variable
Authorization required, but no authorization protocol specified

Error: Invalid argument (os error 22)
```

Then I used sudo -E
```
  sudo -E ./target/debug/persway daemon -w -e '[tiling] opacity 1' -f '[tiling] opacity 0.95; opacity 1' -l 'mark --add _prev' -d stack_main
^C
```

And none of these keybindings in ~/.config/sway/config did anything, at all. Not even a log line in the debug build.
```
#Persway
bindsym Mod4+Control+space exec persway stack-main-rotate-next
bindsym mod4+Shift+Tab exec persway stack-focus-prev
bindsym Mod4+Tab exec persway stack-focus-next
bindsym Mod4+c exec persway change-layout stack-main --size 70 --stack-layout tiled
bindsym Mod4+space exec persway stack-swap-main
bindsym Mod4+v exec persway change-layout manual
bindsym Mod4+x exec persway change-layout stack-main --size 70
bindsym Mod4+z exec persway change-layout spiral
```

I'm just filing this because it doesn't seam like you'd want people to have this experience.

**Comment by johnae** [comment]
Ok. Thanks for the feedback. W.r.t AUR I'm not an arch user myself and I didn't create that package.

Sudo should NOT be used. The only thing persway does is create the control socket in the standard $XDG_RUNTIME_DIR which should (only) be accessible by the current user - that's the point of that directory.

Of course, if there was a persway-wayland-1.sock there already, created by root (sudo) then there'd be a permissions problem. Not saying that is what happened here but again $XDG_RUNTIME_DIR not being accessible by the current user is a problem on your system if indeed that is what's happening.

There may be a bug in persway around creating the control socket which I'll look into. It makes sense that your keybindings wouldn't work when the socket is owned by root anyway so nothing would happen.

In essence - the version in AUR is old, not something I maintain. Using sudo to start persway will lead to problems and should never be necessary either.

**Comment by jeremyjjbrown** [comment]
I'm confused that the socket wasn't able to be created. It didn't exist. I explicitly rm'd the full path just to be 100% sure.

Should I recreate the socket file with my user as the owner and try again? Or should I make sure it is absent again and restart and try again?

**Comment by jeremyjjbrown** [comment]
I left a comment on the AUR package that it should not be used if the owner isn't going to maintain it.

**Comment by johnae** [comment]
Please try starting Persway without any socket present. If there's an error, please post it here. Thanks!

**Comment by jeremyjjbrown** [comment]
```
20:27:49 kochi:~/src/github.com/johnae/persway on main
  ./target/debug/persway daemon -w -e '[tiling] opacity 1' -f '[tiling] opacity 0.95; opacity 1' -l 'mark --add _prev' --default-layout spiral
[2023-05-17T01:28:09Z ERROR persway::server::daemon] Unable to remove stale socket: /run/user/1000/persway-wayland-1.sock
    Custom { kind: NotFound, error: VerboseError { source: Os { code: 2, kind: NotFound, message: "No such file or directory" }, message: "could not remove file `/run/user/1000/persway-wayland-1.sock`" } }
^C
20:28:27 kochi:~/src/github.com/johnae/persway on main
  ls /run/user/1000/
Alacritty-wayland-1-1194.sock  at-spi  dbus-1  doc  gnupg  gvfsd    persway-wayland-1.sock  pipewire-0.lock  rofi.pid                systemd    wayland-1.lock
Alacritty-wayland-1-1734.sock  bus     dconf   gcr  gvfs   p11-kit  pipewire-0              pulse            sway-ipc.1000.962.sock  wayland-1

20:28:39 kochi:~/src/github.com/johnae/persway on main
  rm /run/user/1000/persway-wayland-1.sock

20:29:11 kochi:~/src/github.com/johnae/persway on main
  ls /run/user/1000/
Alacritty-wayland-1-1194.sock  at-spi  dbus-1  doc  gnupg  gvfsd    pipewire-0       pulse     sway-ipc.1000.962.sock  wayland-1
Alacritty-wayland-1-1734.sock  bus     dconf   gcr  gvfs   p11-kit  pipewire-0.lock  rofi.pid  systemd                 wayland-1.lock

20:29:19 kochi:~/src/github.com/johnae/persway on main
  ./target/debug/persway daemon -w -e '[tiling] opacity 1' -f '[tiling] opacity 0.95; opacity 1' -l 'mark --add _prev' --default-layout spiral
[2023-05-17T01:29:22Z ERROR persway::server::daemon] Unable to remove stale socket: /run/user/1000/persway-wayland-1.sock
    Custom { kind: NotFound, error: VerboseError { source: Os { code: 2, kind: NotFound, message: "No such file or directory" }, message: "could not remove file `/run/user/1000/persway-wayland-1.sock`" } }
^C
20:29:28 kochi:~/src/github.com/johnae/persway on main
  ls -al /run/user/1000/persway-wayland-1.sock
srwxr-xr-x 1 jebrown jeremybr 0 May 16 20:29 /run/user/1000/persway-wayland-1.sock
```

Different machine. Also Arch Linux. I built with `cargo build`.

**Comment by johnae** [comment]
That's strange. I'll have to test this myself. Maybe there's a bug in persway here. I'm using persway myself ofc without issues.

**Comment by johnae** [comment]
Also, to actually have persway work properly from within sway - you must use the 0.6.x version that you're also running as a daemon. You can't run the older version from AUR.

**Comment by jeremyjjbrown** [comment]
> can you please try persway with the keybindings in sway and simply ignore the error message? 

I did multiple times on both machines. I will try again though as soon as possible.

**Comment by johnae** [comment]
@jeremyjjbrown As I noted earlier -  please ensure you're using the same version of persway for both daemon and client. Don't know this ofc, but you were previously using an older aur version in the sway config I believe, if that's the client you're using from within sway it will not work against the newer persway version. Please try running the commands manually on the cli first.
